---
request_url: 'http://w0297.uws.edu.au/data_files/api_search'
api_token: 'My_API_Token'

params:
  - variables: ['AirTC']
    dest_dir: '/home/gerarddevine/dev/misc/downloads/AIRTC'
  
  - variables: ['SoilTemp_Avg(1)', 'SoilTemp_Avg(2)']
    dest_dir: '/home/gerarddevine/dev/misc/downloads/SoilTemp_Avg'