#Settings for automated download of HIEv files - used to run hiev_autodownload.py
#
# -- Notes
# - Your API Token can be retrieved from the HIEv account webpage
# - If a dest_dir is not already created, the script will automatically create it
# - Multiple variables can be added under one search
#
# -- Example file:
#  request_url: 'http://w0297.uws.edu.au/data_files/api_search'
#  api_token: 'justadummyapitoken'
#
#  params:
#  - variables: ['AirTC']
#    dirname: 'AIRTC'
#    ingest: ''
#  
#  - variables: ['SoilTemp_Avg(1)', 'SoilTemp_Avg(2)']
#    dirname: 'SoilTemp_Avg'
#    ingest: 'daily'
# --

---
request_url: 'http://hiev.uws.edu.au/data_files/api_search'
api_token: 'My_API_Token'

params:
  - variables: ['Var1']
    dirname: 'DIRECTORY1'
    ingest: '' 
  
  - variables: ['Var2', 'Var3']
    dirname: 'DIRECTORY2'
    ingest: 'daily'
